/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Item {
  'itemId' : ItemId,
  'isChecked' : boolean,
  'name' : string,
  'quantity' : bigint,
  'category' : string,
}
export type ItemId = bigint;
export interface _SERVICE {
  'addItem' : ActorMethod<[string, bigint, string], ItemId>,
  'clearAllItems' : ActorMethod<[], undefined>,
  'clearCheckedItems' : ActorMethod<[], undefined>,
  'deleteItem' : ActorMethod<[ItemId], undefined>,
  'getAllItems' : ActorMethod<[], Array<Item>>,
  'markItemChecked' : ActorMethod<[ItemId, boolean], undefined>,
  'toggleItemChecked' : ActorMethod<[ItemId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];