/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemId = IDL.Nat;
export const Item = IDL.Record({
  'itemId' : ItemId,
  'isChecked' : IDL.Bool,
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [ItemId], []),
  'clearAllItems' : IDL.Func([], [], []),
  'clearCheckedItems' : IDL.Func([], [], []),
  'deleteItem' : IDL.Func([ItemId], [], []),
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'markItemChecked' : IDL.Func([ItemId, IDL.Bool], [], []),
  'toggleItemChecked' : IDL.Func([ItemId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemId = IDL.Nat;
  const Item = IDL.Record({
    'itemId' : ItemId,
    'isChecked' : IDL.Bool,
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [ItemId], []),
    'clearAllItems' : IDL.Func([], [], []),
    'clearCheckedItems' : IDL.Func([], [], []),
    'deleteItem' : IDL.Func([ItemId], [], []),
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'markItemChecked' : IDL.Func([ItemId, IDL.Bool], [], []),
    'toggleItemChecked' : IDL.Func([ItemId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };